### PR TITLE
Fix slice out of bounds crash

### PR DESCRIPTION
**Pull request by nikandfor**
There was crash when we trying to insert element to full data struct at position i=0
when left neighbour data struct was not full

### CODE REVIEW

**Comment by cznic** [comment]
Thank you very much for the report and the PR. The bug you have found is real, but the fix is unfortunately not correct.

Let's consider this is added to `all_test.go`:

```bash
jnml@4670:~/src/github.com/cznic/b$ git diff all_test.go
diff --git a/all_test.go b/all_test.go
index aec5a60..1674285 100644
--- a/all_test.go
+++ b/all_test.go
@@ -1330,3 +1330,22 @@ func TestSeek(t *testing.T) {
                }
        }
 }
+
+func TestPR4(t *testing.T) {
+       tr := TreeNew(cmp)
+       for i := 0; i < 2*kd+1; i++ {
+               k := 1000 * i
+               tr.Set(k, nil)
+       }
+       tr.Delete(1000 * kd)
+       for i := 0; i < kd; i++ {
+               tr.Set(1000*(kd+1)-1-i, nil)
+       }
+       k := 1000*(kd+1) - 1 - kd
+       dbg("\n==== Before split\n%v", tr.dump())
+       tr.Set(k, nil)
+       dbg("\n==== After split\n%v", tr.dump())
+       if _, ok := tr.Get(k); !ok {
+               t.Fatalf("key lost: %v", k)
+       }
+}
jnml@4670:~/src/github.com/cznic/b$ 
```

Without you patch the test now reproduces the crash:

```bash
jnml@4670:~/src/github.com/cznic/b$ go test -run PR4
all_test.go:1345: 
==== Before split
X#1(0xc8200ad200) n 1:2 {(C#2 K 32000) (C#3 K <nil>)}
. D#2(0xc8200ac000) P#0 N#3 n 32:32 {0:<nil> 1000:<nil> 2000:<nil> 3000:<nil> 4000:<nil> 5000:<nil> 6000:<nil> 7000:<nil> 8000:<nil> 9000:<nil> 10000:<nil> 11000:<nil> 12000:<nil> 13000:<nil> 14000:<nil> 15000:<nil> 16000:<nil> 17000:<nil> 18000:<nil> 19000:<nil> 20000:<nil> 21000:<nil> 22000:<nil> 23000:<nil> 24000:<nil> 25000:<nil> 26000:<nil> 27000:<nil> 28000:<nil> 29000:<nil> 30000:<nil> 31000:<nil>}
. D#3(0xc8200ac900) P#2 N#0 n 64:64 {32968:<nil> 32969:<nil> 32970:<nil> 32971:<nil> 32972:<nil> 32973:<nil> 32974:<nil> 32975:<nil> 32976:<nil> 32977:<nil> 32978:<nil> 32979:<nil> 32980:<nil> 32981:<nil> 32982:<nil> 32983:<nil> 32984:<nil> 32985:<nil> 32986:<nil> 32987:<nil> 32988:<nil> 32989:<nil> 32990:<nil> 32991:<nil> 32992:<nil> 32993:<nil> 32994:<nil> 32995:<nil> 32996:<nil> 32997:<nil> 32998:<nil> 32999:<nil> 33000:<nil> 34000:<nil> 35000:<nil> 36000:<nil> 37000:<nil> 38000:<nil> 39000:<nil> 40000:<nil> 41000:<nil> 42000:<nil> 43000:<nil> 44000:<nil> 45000:<nil> 46000:<nil> 47000:<nil> 48000:<nil> 49000:<nil> 50000:<nil> 51000:<nil> 52000:<nil> 53000:<nil> 54000:<nil> 55000:<nil> 56000:<nil> 57000:<nil> 58000:<nil> 59000:<nil> 60000:<nil> 61000:<nil> 62000:<nil> 63000:<nil> 64000:<nil>}
--- FAIL: TestPR4 (0.00s)
panic: runtime error: slice bounds out of range [recovered]
	panic: runtime error: slice bounds out of range

goroutine 5 [running]:
testing.tRunner.func1(0xc8200aa000)
	/home/jnml/go/src/testing/testing.go:450 +0x171
github.com/cznic/b.(*Tree).overflow(0xc8200166c0, 0xc8200ad200, 0xc8200ac900, 0x1, 0x0, 0x562540, 0xc8200b3480, 0x0, 0x0)
	/home/jnml/src/github.com/cznic/b/btree.go:455 +0x611
github.com/cznic/b.(*Tree).Set(0xc8200166c0, 0x562540, 0xc8200b3480, 0x0, 0x0)
	/home/jnml/src/github.com/cznic/b/btree.go:576 +0xa76
github.com/cznic/b.TestPR4(0xc8200aa000)
	/home/jnml/src/github.com/cznic/b/all_test.go:1346 +0x2f6
testing.tRunner(0xc8200aa000, 0x6dcdf8)
	/home/jnml/go/src/testing/testing.go:456 +0x98
created by testing.RunTests
	/home/jnml/go/src/testing/testing.go:561 +0x86d

goroutine 1 [chan receive]:
testing.RunTests(0x62a158, 0x6dcc00, 0x16, 0x16, 0x6e6d6c6b6a696801)
	/home/jnml/go/src/testing/testing.go:562 +0x8ad
testing.(*M).Run(0xc820093ee8, 0x161514131211100f)
	/home/jnml/go/src/testing/testing.go:494 +0x70
main.main()
	github.com/cznic/b/_test/_testmain.go:176 +0x116
exit status 2
FAIL	github.com/cznic/b	0.004s
jnml@4670:~/src/github.com/cznic/b$ 
```

With your patch the test does not crash anymore, but the last inserted key is now on the wrong side of the pivot key of the index page:

```bash
jnml@4670:~/src/github.com/cznic/b$ go test -run PR4
all_test.go:1345: 
==== Before split
X#1(0xc8200ad200) n 1:2 {(C#2 K 32000) (C#3 K <nil>)}
. D#2(0xc8200ac000) P#0 N#3 n 32:32 {0:<nil> 1000:<nil> 2000:<nil> 3000:<nil> 4000:<nil> 5000:<nil> 6000:<nil> 7000:<nil> 8000:<nil> 9000:<nil> 10000:<nil> 11000:<nil> 12000:<nil> 13000:<nil> 14000:<nil> 15000:<nil> 16000:<nil> 17000:<nil> 18000:<nil> 19000:<nil> 20000:<nil> 21000:<nil> 22000:<nil> 23000:<nil> 24000:<nil> 25000:<nil> 26000:<nil> 27000:<nil> 28000:<nil> 29000:<nil> 30000:<nil> 31000:<nil>}
. D#3(0xc8200ac900) P#2 N#0 n 64:64 {32968:<nil> 32969:<nil> 32970:<nil> 32971:<nil> 32972:<nil> 32973:<nil> 32974:<nil> 32975:<nil> 32976:<nil> 32977:<nil> 32978:<nil> 32979:<nil> 32980:<nil> 32981:<nil> 32982:<nil> 32983:<nil> 32984:<nil> 32985:<nil> 32986:<nil> 32987:<nil> 32988:<nil> 32989:<nil> 32990:<nil> 32991:<nil> 32992:<nil> 32993:<nil> 32994:<nil> 32995:<nil> 32996:<nil> 32997:<nil> 32998:<nil> 32999:<nil> 33000:<nil> 34000:<nil> 35000:<nil> 36000:<nil> 37000:<nil> 38000:<nil> 39000:<nil> 40000:<nil> 41000:<nil> 42000:<nil> 43000:<nil> 44000:<nil> 45000:<nil> 46000:<nil> 47000:<nil> 48000:<nil> 49000:<nil> 50000:<nil> 51000:<nil> 52000:<nil> 53000:<nil> 54000:<nil> 55000:<nil> 56000:<nil> 57000:<nil> 58000:<nil> 59000:<nil> 60000:<nil> 61000:<nil> 62000:<nil> 63000:<nil> 64000:<nil>}
all_test.go:1347: 
==== After split
X#1(0xc8200ad200) n 1:2 {(C#2 K 32000) (C#3 K <nil>)}
. D#2(0xc8200ac000) P#0 N#3 n 33:33 {0:<nil> 1000:<nil> 2000:<nil> 3000:<nil> 4000:<nil> 5000:<nil> 6000:<nil> 7000:<nil> 8000:<nil> 9000:<nil> 10000:<nil> 11000:<nil> 12000:<nil> 13000:<nil> 14000:<nil> 15000:<nil> 16000:<nil> 17000:<nil> 18000:<nil> 19000:<nil> 20000:<nil> 21000:<nil> 22000:<nil> 23000:<nil> 24000:<nil> 25000:<nil> 26000:<nil> 27000:<nil> 28000:<nil> 29000:<nil> 30000:<nil> 31000:<nil> 32967:<nil>}
. D#3(0xc8200ac900) P#2 N#0 n 64:64 {32968:<nil> 32969:<nil> 32970:<nil> 32971:<nil> 32972:<nil> 32973:<nil> 32974:<nil> 32975:<nil> 32976:<nil> 32977:<nil> 32978:<nil> 32979:<nil> 32980:<nil> 32981:<nil> 32982:<nil> 32983:<nil> 32984:<nil> 32985:<nil> 32986:<nil> 32987:<nil> 32988:<nil> 32989:<nil> 32990:<nil> 32991:<nil> 32992:<nil> 32993:<nil> 32994:<nil> 32995:<nil> 32996:<nil> 32997:<nil> 32998:<nil> 32999:<nil> 33000:<nil> 34000:<nil> 35000:<nil> 36000:<nil> 37000:<nil> 38000:<nil> 39000:<nil> 40000:<nil> 41000:<nil> 42000:<nil> 43000:<nil> 44000:<nil> 45000:<nil> 46000:<nil> 47000:<nil> 48000:<nil> 49000:<nil> 50000:<nil> 51000:<nil> 52000:<nil> 53000:<nil> 54000:<nil> 55000:<nil> 56000:<nil> 57000:<nil> 58000:<nil> 59000:<nil> 60000:<nil> 61000:<nil> 62000:<nil> 63000:<nil> 64000:<nil>}
--- FAIL: TestPR4 (0.00s)
	all_test.go:1349: key lost: 32967
FAIL
exit status 1
FAIL	github.com/cznic/b	0.002s
jnml@4670:~/src/github.com/cznic/b$ 
```

I suggest to change your PR according to, for example:

```bash
jnml@4670:~/src/github.com/cznic/b$ git diff btree.go
diff --git a/btree.go b/btree.go
index baff42c..dbb40ec 100644
--- a/btree.go
+++ b/btree.go
@@ -452,7 +452,10 @@ func (t *Tree) overflow(p *x, q *d, pi, i int, k interface{} /*K*/, v interface{
 
        if l != nil && l.c < 2*kd {
                l.mvL(q, 1)
-               t.insert(q, i-1, k, v)
+               if i > 0 {
+                       i--
+               }
+               t.insert(q, i, k, v)
                p.x[pi-1].k = q.d[0].k
                return
        }
jnml@4670:~/src/github.com/cznic/b$ 
```

With this modification all tests pass.

Also, please add yourself to the [CONTRIBUTORS](https://github.com/cznic/b/blob/master/CONTRIBUTORS) file so I can merge the new PR, thank you.

**Comment by cznic** [comment]
I believe this is correct:

```bash
jnml@4670:~/src/github.com/cznic/b$ git diff btree.go
diff --git a/btree.go b/btree.go
index baff42c..882e371 100644
--- a/btree.go
+++ b/btree.go
@@ -450,7 +450,7 @@ func (t *Tree) overflow(p *x, q *d, pi, i int, k interface{} /*K*/, v interface{
        t.ver++
        l, r := p.siblings(pi)
 
-       if l != nil && l.c < 2*kd {
+       if l != nil && l.c < 2*kd && i != 0 {
                l.mvL(q, 1)
                t.insert(q, i-1, k, v)
                p.x[pi-1].k = q.d[0].k
jnml@4670:~/src/github.com/cznic/b$ 
```

```bash
jnml@4670:~/src/github.com/cznic/b$ go test -run PR4
all_test.go:1345: 
==== Before split
X#1(0xc8200ad200) n 1:2 {(C#2 K 32000) (C#3 K <nil>)}
. D#2(0xc8200ac000) P#0 N#3 n 32:32 {0:<nil> 1000:<nil> 2000:<nil> 3000:<nil> 4000:<nil> 5000:<nil> 6000:<nil> 7000:<nil> 8000:<nil> 9000:<nil> 10000:<nil> 11000:<nil> 12000:<nil> 13000:<nil> 14000:<nil> 15000:<nil> 16000:<nil> 17000:<nil> 18000:<nil> 19000:<nil> 20000:<nil> 21000:<nil> 22000:<nil> 23000:<nil> 24000:<nil> 25000:<nil> 26000:<nil> 27000:<nil> 28000:<nil> 29000:<nil> 30000:<nil> 31000:<nil>}
. D#3(0xc8200ac900) P#2 N#0 n 64:64 {32968:<nil> 32969:<nil> 32970:<nil> 32971:<nil> 32972:<nil> 32973:<nil> 32974:<nil> 32975:<nil> 32976:<nil> 32977:<nil> 32978:<nil> 32979:<nil> 32980:<nil> 32981:<nil> 32982:<nil> 32983:<nil> 32984:<nil> 32985:<nil> 32986:<nil> 32987:<nil> 32988:<nil> 32989:<nil> 32990:<nil> 32991:<nil> 32992:<nil> 32993:<nil> 32994:<nil> 32995:<nil> 32996:<nil> 32997:<nil> 32998:<nil> 32999:<nil> 33000:<nil> 34000:<nil> 35000:<nil> 36000:<nil> 37000:<nil> 38000:<nil> 39000:<nil> 40000:<nil> 41000:<nil> 42000:<nil> 43000:<nil> 44000:<nil> 45000:<nil> 46000:<nil> 47000:<nil> 48000:<nil> 49000:<nil> 50000:<nil> 51000:<nil> 52000:<nil> 53000:<nil> 54000:<nil> 55000:<nil> 56000:<nil> 57000:<nil> 58000:<nil> 59000:<nil> 60000:<nil> 61000:<nil> 62000:<nil> 63000:<nil> 64000:<nil>}
all_test.go:1347: 
==== After split
X#1(0xc8200ad200) n 2:3 {(C#2 K 32000) (C#3 K 33000) (C#4 K <nil>)}
. D#2(0xc8200ac000) P#0 N#3 n 32:32 {0:<nil> 1000:<nil> 2000:<nil> 3000:<nil> 4000:<nil> 5000:<nil> 6000:<nil> 7000:<nil> 8000:<nil> 9000:<nil> 10000:<nil> 11000:<nil> 12000:<nil> 13000:<nil> 14000:<nil> 15000:<nil> 16000:<nil> 17000:<nil> 18000:<nil> 19000:<nil> 20000:<nil> 21000:<nil> 22000:<nil> 23000:<nil> 24000:<nil> 25000:<nil> 26000:<nil> 27000:<nil> 28000:<nil> 29000:<nil> 30000:<nil> 31000:<nil>}
. D#3(0xc8200ac900) P#2 N#4 n 33:33 {32967:<nil> 32968:<nil> 32969:<nil> 32970:<nil> 32971:<nil> 32972:<nil> 32973:<nil> 32974:<nil> 32975:<nil> 32976:<nil> 32977:<nil> 32978:<nil> 32979:<nil> 32980:<nil> 32981:<nil> 32982:<nil> 32983:<nil> 32984:<nil> 32985:<nil> 32986:<nil> 32987:<nil> 32988:<nil> 32989:<nil> 32990:<nil> 32991:<nil> 32992:<nil> 32993:<nil> 32994:<nil> 32995:<nil> 32996:<nil> 32997:<nil> 32998:<nil> 32999:<nil>}
. D#4(0xc8200adb00) P#3 N#0 n 32:32 {33000:<nil> 34000:<nil> 35000:<nil> 36000:<nil> 37000:<nil> 38000:<nil> 39000:<nil> 40000:<nil> 41000:<nil> 42000:<nil> 43000:<nil> 44000:<nil> 45000:<nil> 46000:<nil> 47000:<nil> 48000:<nil> 49000:<nil> 50000:<nil> 51000:<nil> 52000:<nil> 53000:<nil> 54000:<nil> 55000:<nil> 56000:<nil> 57000:<nil> 58000:<nil> 59000:<nil> 60000:<nil> 61000:<nil> 62000:<nil> 63000:<nil> 64000:<nil>}
PASS
ok  	github.com/cznic/b	0.001s
jnml@4670:~/src/github.com/cznic/b$ 
```

Please double check this result, so we can be confident to not introduce a new bug, thank you.

**Comment by nikandfor** [comment]
My first idea was
```
diff --git a/btree.go b/btree.go
index baff42c..882e371 100644
--- a/btree.go
+++ b/btree.go
@@ -450,7 +450,7 @@ func (t *Tree) overflow(p *x, q *d, pi, i int, k interface{} /*K*/, v interface{
        t.ver++
        l, r := p.siblings(pi)

-       if l != nil && l.c < 2*kd {
+       if l != nil && l.c < 2*kd && i > 0 {
                l.mvL(q, 1)
                t.insert(q, i-1, k, v)
                p.x[pi-1].k = q.d[0].k
```
Then I decide it should be like next if about right neigbour. :)
Your solution is good I think

**Comment by cznic** [comment]
Thanks a lot!

**Comment by nikandfor** [comment]
Thank you for good btree

**Pull request merged**
